//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionWeb.ServiceWCFNegocio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WCFNegocio.Models")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFormateadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassworldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFormateada {
            get {
                return this.FechaFormateadaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFormateadaField, value) != true)) {
                    this.FechaFormateadaField = value;
                    this.RaisePropertyChanged("FechaFormateada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passworld {
            get {
                return this.PassworldField;
            }
            set {
                if ((object.ReferenceEquals(this.PassworldField, value) != true)) {
                    this.PassworldField = value;
                    this.RaisePropertyChanged("Passworld");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCFNegocio.IUsuarioServices")]
    public interface IUsuarioServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/GuardarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/GuardarUsuarioResponse")]
        bool GuardarUsuario(PresentacionWeb.ServiceWCFNegocio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/GuardarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/GuardarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> GuardarUsuarioAsync(PresentacionWeb.ServiceWCFNegocio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(PresentacionWeb.ServiceWCFNegocio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(PresentacionWeb.ServiceWCFNegocio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/EliminarUsuarioResponse")]
        bool EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ConsultarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/ConsultarUsuarioResponse")]
        PresentacionWeb.ServiceWCFNegocio.Usuario ConsultarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ConsultarUsuario", ReplyAction="http://tempuri.org/IUsuarioServices/ConsultarUsuarioResponse")]
        System.Threading.Tasks.Task<PresentacionWeb.ServiceWCFNegocio.Usuario> ConsultarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ListartUsuarios", ReplyAction="http://tempuri.org/IUsuarioServices/ListartUsuariosResponse")]
        PresentacionWeb.ServiceWCFNegocio.Usuario[] ListartUsuarios(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/ListartUsuarios", ReplyAction="http://tempuri.org/IUsuarioServices/ListartUsuariosResponse")]
        System.Threading.Tasks.Task<PresentacionWeb.ServiceWCFNegocio.Usuario[]> ListartUsuariosAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServicesChannel : PresentacionWeb.ServiceWCFNegocio.IUsuarioServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServicesClient : System.ServiceModel.ClientBase<PresentacionWeb.ServiceWCFNegocio.IUsuarioServices>, PresentacionWeb.ServiceWCFNegocio.IUsuarioServices {
        
        public UsuarioServicesClient() {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarUsuario(PresentacionWeb.ServiceWCFNegocio.Usuario usuario) {
            return base.Channel.GuardarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarUsuarioAsync(PresentacionWeb.ServiceWCFNegocio.Usuario usuario) {
            return base.Channel.GuardarUsuarioAsync(usuario);
        }
        
        public bool ActualizarUsuario(PresentacionWeb.ServiceWCFNegocio.Usuario usuario) {
            return base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(PresentacionWeb.ServiceWCFNegocio.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public bool EliminarUsuario(int id) {
            return base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public PresentacionWeb.ServiceWCFNegocio.Usuario ConsultarUsuario(int id) {
            return base.Channel.ConsultarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<PresentacionWeb.ServiceWCFNegocio.Usuario> ConsultarUsuarioAsync(int id) {
            return base.Channel.ConsultarUsuarioAsync(id);
        }
        
        public PresentacionWeb.ServiceWCFNegocio.Usuario[] ListartUsuarios(string nombre) {
            return base.Channel.ListartUsuarios(nombre);
        }
        
        public System.Threading.Tasks.Task<PresentacionWeb.ServiceWCFNegocio.Usuario[]> ListartUsuariosAsync(string nombre) {
            return base.Channel.ListartUsuariosAsync(nombre);
        }
    }
}
